# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
      - created

# workflow tasks
jobs:
  zip:
    name: Generate windows binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files zip
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'windows/amd64, windows/386'
          package: ''
          name: 'starman'
          compress: 'true'
          dest: 'dist'
      - name: Setup GO env
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Build go binaries
        run: |
          go version
          GOOS=windows GOARCH=amd64 go build -ldflags "-w" -o starman-amd64.exe
          GOOS=windows GOARCH=386 go build -ldflags "-w" -o starman-i386.exe
          gh release upload $RELEASE_VERSION starman-amd64.exe starman-i386.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
